import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yelinaung' at '7/10/15 12:18 AM' with Gradle 2.4
 *
 * @author yelinaung, @date 7/10/15 12:18 AM
 */
public class RabbitTest {
    @Test public void testSomeLibraryMethod() {
        Rabbit classUnderTest = new Rabbit();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
