import org.junit.Test;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'yelinaung' at '7/10/15 12:18 AM' with Gradle 2.4
 *
 * @author yelinaung, @date 7/10/15 12:18 AM
 */
public class RabbitTest {

  private String zgString = "မဂၤလာပါ";
  private String uniString = "မင်္ဂလာပါ";

  @Test public void testUni2Zawgyi() {
    assertEquals(zgString, Rabbit.uni2zg(uniString));
  }

  @Test public void testZawgyi2Uni() {
    assertEquals(uniString, Rabbit.zg2uni(zgString));
  }
}
